---
version: '2'
services:
  mongodb:
    image: "mongo:4.0.16"
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017-27019:27017-27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'flaskUser'
      MONGO_INITDB_ROOT_PASSWORD: 'jmhcQNHk0l'
  pymongo:
    build: ./alias_backend/backend
    hostname: pymongo
    container_name: pymongo
    ports:
      - "5000:5000"
    depends_on: 
      - mongodb
  correctness:
    build: ./alias_backend/correctness
    hostname: correctness
    container_name: correctness
    ports:
      - "5001:5001"
  frontend:
    build: ./aliasFrontend
    hostname: frontend
    container_name: frontend
    depends_on:
      - mongodb
      - pymongo
    ports:
      - "80:80"