---
version: '3'
services:
  mongodb:
    #build: ./db
    image: mongo:4.0.16
    hostname: mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
    #  - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
    #  - MONGO_INITDB_DATABASE=admin
    #  - MONGO_ROOT_USER=${MONGO_ROOT_USER}
    #  - MONGO_ROOT_PASS=${MONGO_ROOT_PASS}
    #  - APP_MONGO_PASS=${APP_MONGO_PASS}
    #  - APP_MONGO_USER=${APP_MONGO_USER}
    #  - APP_MONGO_DB=${APP_MONGO_DB}
    #volumes:
    #The Path for mount needs to be defined here
    #    #But WSL with the Docker for Windows Daemon (which i am currently using)
    #  - /where/to/store/your/mongodb/data:/data/db
    #  - ./db/create-user.sh:/docker-entrypoint-initdb.d/create-user.sh:ro
    #command: mongod
  pymongo:
    build: ./alias_backend/backend
    hostname: pymongo
    container_name: pymongo
    ports:
      - "5000:5000"
    depends_on: 
      - mongodb
  #correctness:
  #  build: ./alias_backend/correctness
  #  hostname: correctness
  #  container_name: correctness
  #  ports:
  #    - "5010:5010"
  #  depends_on:
  #    - pymongo
  frontend:
    build: ./aliasFrontend
    hostname: frontend
    container_name: frontend
    depends_on:
      - mongodb
      - pymongo
    ports:
      - "5020:80"
