---
version: '3'
services:
  mongodb:
    #Build and environment if u want to use a DB-User
    #build: ./db
    image: mongo:4.0.16
    hostname: mongodb
    container_name: mongodb
    #The Mongo-DB-Ports just need to be opened, when you run the pymongo app on localhost instead inside docker network
    #ports:
    #  - 27017:27017
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
    #  - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
    #  - MONGO_INITDB_DATABASE=admin
    #  - MONGO_ROOT_USER=${MONGO_ROOT_USER}
    #  - MONGO_ROOT_PASS=${MONGO_ROOT_PASS}
    #  - APP_MONGO_PASS=${APP_MONGO_PASS}
    #  - APP_MONGO_USER=${APP_MONGO_USER}
    #  - APP_MONGO_DB=${APP_MONGO_DB}
    #Define the Path to mount the Data of Database
    #volumes:
    #  - /where/to/store/your/mongodb/data:/data/db
  pymongo:
    build: ./alias_backend/backend
    hostname: pymongo
    container_name: pymongo
    ports:
      - "5000:5000"
    depends_on: 
      - mongodb
  correctness:
    build: ./alias_backend/correctness
    hostname: correctness
    container_name: correctness
    ports:
      - "5010:5010"
    depends_on:
      - pymongo
  frontend:
    build: ./aliasFrontend
    hostname: frontend
    container_name: frontend
    depends_on:
      - mongodb
      - pymongo
    ports:
      - "80:80"
